server:
  port: 8081
upload:
  path: ./upload_files
  topic: pricefeed_offer
spring:
  data:
    mongodb:
      #uri: mongodb+srv://root:example@localhost/offer
      database: offer
      host: localhost
      password: example
      user: root
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: latest
      group-id: pricefeed-dev
      properties:
        spring:
          json:
            trusted:
              packages: kz.ks.*
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      client-id: pricefeed-dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'true'
org:
  jobrunr:
    database:
      type: sql
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
logging:
  level:
    kz:
      ks: DEBUG
springdoc:
  swagger-ui:
    enabled: true
  packages-to-scan: kz.ks